baseURL = "https://echoesparis.github.io/slides/"
languageCode = "en-us"
title = "Slides"
theme = "reveal-hugo"
publishDir = "docs"

[markup.goldmark.renderer]
unsafe = true

[outputFormats.Reveal]
baseName = "index"
mediaType = "text/html"
isHTML = true

[params]
author = "SP"
email = "sp@echoes.paris"

[params.reveal_hugo]
custom_theme = "reveal-hugo/themes/static-custom-theme.css"
